### ISSUE TITLE
Database View query

### ISSUE THREAD

**Issue by devpro** [rabbids-incubator/servicenow-dotnet-client#10]

**Comment by devpro** [comment]
Feature has been implemented.

How to setup?

- Edit `entities.yml` with a new type of query.findall property

```yaml
entities:
  - name: DatabaseInventory
    resourceName: db-inventories
    queries:
      findAll:
        sqlServerDatabaseTable: Inventory
    fields:
      - name: Id
        mapFrom: CMDB_ID
      - name: Name
        mapFrom: Name
      - name: Quantity
        mapFrom: Qty
        fieldType: Number
      - name: IsStackMember
        mapFrom: Is_stack_Member
        fieldType: Boolean
```

- Add configuration (json or environment variables)

```
{
  "ServiceNow": {
    "SqlServer": {
      "DataSource": "127.0.0.1",
      "UserId": "SA",
      "Password": "<sqlserverpassword>",
      "InitialCatalog": "TestDB"
    }
  }
}
```
